/* Generated by scripts/generate_ipc_contract.py. Do not edit. */
export const COMMAND_SPECS = {
  "ping": {
    "params": {}
  },
  "health": {
    "params": {}
  },
  "shutdown": {
    "params": {}
  },
  "get_state": {
    "params": {}
  },
  "snapshot": {
    "params": {}
  },
  "get_vowel_analysis": {
    "params": {
      "index": "int",
      "sections": "string[]"
    },
    "required": [
      "index"
    ]
  },
  "set_analysis_settings": {
    "params": {
      "settings": "object"
    },
    "required": [
      "settings"
    ]
  },
  "load_files": {
    "params": {
      "paths": "string[]"
    },
    "required": [
      "paths"
    ]
  },
  "remove_file": {
    "params": {
      "index": "int"
    },
    "required": [
      "index"
    ]
  },
  "set_current_index": {
    "params": {
      "index": "int"
    },
    "required": [
      "index"
    ]
  },
  "reset": {
    "params": {}
  },
  "save_project": {
    "params": {
      "path": "string"
    },
    "required": [
      "path"
    ]
  },
  "load_project": {
    "params": {
      "path": "string"
    },
    "required": [
      "path"
    ]
  },
  "export_combined_txt": {
    "params": {
      "path": "string"
    },
    "required": [
      "path"
    ]
  },
  "open_single_plot": {
    "params": {}
  },
  "open_compare": {
    "params": {
      "source_groups": "int[][]",
      "normalization": "string|null"
    },
    "required": [
      "source_groups"
    ]
  },
  "open_guide": {
    "params": {}
  },
  "request_preview": {
    "params": {
      "request_id": "int"
    }
  },
  "measure_distance": {
    "params": {
      "x1": "number",
      "y1": "number",
      "x2": "number",
      "y2": "number"
    },
    "required": [
      "x1",
      "y1",
      "x2",
      "y2"
    ]
  },
  "export_interactive_preview": {
    "params": {
      "path": "string",
      "format": "string",
      "options": "interactive_options"
    },
    "required": [
      "path",
      "format",
      "options"
    ]
  },
  "export_interactive_batch": {
    "params": {
      "directory": "string",
      "format": "string",
      "options": "interactive_options"
    },
    "required": [
      "directory",
      "format",
      "options"
    ]
  },
  "update_interactive_session": {
    "params": {
      "options": "interactive_options"
    },
    "required": [
      "options"
    ]
  },
  "render_interactive_preview": {
    "params": {
      "options": "interactive_options"
    },
    "required": [
      "options"
    ]
  },
  "navigate_interactive_preview": {
    "params": {
      "index": "int",
      "options": "interactive_options"
    },
    "required": [
      "index",
      "options"
    ]
  }
} as const;
