"""Generate frontend IPC artifacts from the Python protocol source of truth."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from core.ipc.protocol import COMMANDS, protocol_manifest

SCHEMA_PATH = ROOT / "desktop" / "ipc" / "schema.json"
COMMAND_SPECS_PATH = ROOT / "desktop" / "ipc" / "command-specs.ts"


def render_schema() -> str:
    return json.dumps(protocol_manifest(), ensure_ascii=False, indent=2) + "\n"


def render_command_specs() -> str:
    payload = json.dumps(COMMANDS, ensure_ascii=False, indent=2)
    return (
        "/* Generated by scripts/generate_ipc_contract.py. Do not edit. */\n"
        f"export const COMMAND_SPECS = {payload} as const;\n"
    )


def generated_files() -> dict[Path, str]:
    return {
        SCHEMA_PATH: render_schema(),
        COMMAND_SPECS_PATH: render_command_specs(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale: list[Path] = []
    for path, expected in generated_files().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8", newline="\n")
    if stale:
        for path in stale:
            print(f"stale IPC artifact: {path.relative_to(ROOT)}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
